name: build-and-test

on:
  push:
    branches:
      - github-actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Validate required secrets
        run: |
          test -n "${{ secrets.EC2_HOST }}" || { echo "EC2_HOST is empty"; exit 1; }
          test -n "${{ secrets.EC2_USER }}" || { echo "EC2_USER is empty"; exit 1; }
          test -n "${{ secrets.EC2_SSH_KEY }}" || { echo "EC2_SSH_KEY is empty"; exit 1; }

      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user
            ./deploy.sh
