# .github/workflows/secrets-check.yml
name: Secrets check
on: workflow_dispatch
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure required secrets are set
        run: |
          for v in EC2_HOST EC2_USER EC2_SSH_KEY SERVICE_NAME; do
            if [ -z "${!v}" ]; then
              echo "::error::$v is EMPTY or missing"
              exit 1
            else
              echo "$v is set"
            fi
          done
        env:
          EC2_HOST:     ${{ secrets.EC2_HOST }}
          EC2_USER:     ${{ secrets.EC2_USER }}
          EC2_SSH_KEY:  ${{ secrets.EC2_SSH_KEY }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
